# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=false

neo_version=21.11.38-beta
mc_version=1.21.11

jei_version=27.4.0.15
geckolib_version=5.4.2
terrablender_version=1.21.11-21.11.0.0
