modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"

[[mods]]
modId="pochimod"
version="0.0.5-1.21.1"
displayName="Echoes of Eco"
logoFile="EchoesofEco.png"
credits="Pochi"
authors="Pochi"
description='''
Echoes of Eco - A nature and ecology focused mod for Minecraft.
'''

[[dependencies.pochimod]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pochimod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pochimod]]
    modId="terrablender"
    type="required"
    versionRange="[4.1.0,)"
    ordering="NONE"
    side="BOTH"
