package net.pochi.pochimod.datagen;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;
import net.pochi.pochimod.PochiMod;
import net.pochi.pochimod.block.ModBlocks;
import net.pochi.pochimod.effect.ModEffects;
import net.pochi.pochimod.entity.ModEntityTypes;
import net.pochi.pochimod.item.ModItems;

public abstract class ModLangProvider extends LanguageProvider {
    public ModLangProvider(PackOutput output, String locale) {
        super(output, PochiMod.MOD_ID, locale);
    }
    
    public static class ModLangJP extends ModLangProvider {

        public ModLangJP(PackOutput output) {
            super(output, "ja_jp");
        }

        @Override
        protected void addTranslations() {
            this.add(ModBlocks.CABERNET_SAUVIGNON_LOG.get(), "カベルネ・ソーヴィニョンの原木");
            this.add(ModBlocks.CABERNET_SAUVIGNON_WOOD.get(), "カベルネ・ソーヴィニョンの木");
            this.add(ModBlocks.STRIPPED_CABERNET_SAUVIGNON_LOG.get(), "樹皮を剥いだカベルネ・ソーヴィニョンの原木");
            this.add(ModBlocks.STRIPPED_CABERNET_SAUVIGNON_WOOD.get(), "樹皮を剥いだカベルネ・ソーヴィニョンの木");
            this.add(ModBlocks.CABERNET_SAUVIGNON_PLANKS.get(), "カベルネ・ソーヴィニョンの板材");
            this.add(ModBlocks.CABERNET_SAUVIGNON_LEAVES.get(), "カベルネ・ソーヴィニョンの葉");
            this.add(ModBlocks.CABERNET_SAUVIGNON_SAPLING.get(), "カベルネ・ソーヴィニョンの苗木");
            this.add(ModBlocks.MAPLE_LOG.get(), "メープルの原木");
            this.add(ModBlocks.MAPLE_WOOD.get(), "メープルの木");
            this.add(ModBlocks.STRIPPED_MAPLE_LOG.get(), "樹皮を剥いだメープルの原木");
            this.add(ModBlocks.STRIPPED_MAPLE_WOOD.get(), "樹皮を剥いだメープルの木");
            this.add(ModBlocks.MAPLE_PLANKS.get(), "メープルの板材");
            this.add(ModBlocks.MAPLE_LEAVES.get(), "メープルの葉");
            this.add(ModBlocks.MAPLE_SAPLING.get(), "メープルの苗木");
            this.add(ModBlocks.CINNAMON_LOG.get(), "シナモンの原木");
            this.add(ModBlocks.CINNAMON_WOOD.get(), "シナモンの木");
            this.add(ModBlocks.STRIPPED_CINNAMON_LOG.get(), "樹皮を剥いだシナモンの原木");
            this.add(ModBlocks.STRIPPED_CINNAMON_WOOD.get(), "樹皮を剥いだシナモンの木");
            this.add(ModBlocks.CINNAMON_PLANKS.get(), "シナモンの板材");
            this.add(ModBlocks.CINNAMON_LEAVES.get(), "シナモンの葉");
            this.add(ModBlocks.CINNAMON_SAPLING.get(), "シナモンの苗木");
            this.add(ModBlocks.COLA_LOG.get(), "コーラの原木");
            this.add(ModBlocks.COLA_WOOD.get(), "コーラの木");
            this.add(ModBlocks.STRIPPED_COLA_LOG.get(), "樹皮を剥いだコーラの原木");
            this.add(ModBlocks.STRIPPED_COLA_WOOD.get(), "樹皮を剥いだコーラの木");
            this.add(ModBlocks.COLA_PLANKS.get(), "コーラの板材");
            this.add(ModBlocks.COLA_LEAVES.get(), "コーラの葉");
            this.add(ModBlocks.COLA_SAPLING.get(), "コーラの苗木");
            this.add(ModBlocks.LEMON_LOG.get(), "レモンの原木");
            this.add(ModBlocks.LEMON_WOOD.get(), "レモンの木");
            this.add(ModBlocks.STRIPPED_LEMON_LOG.get(), "樹皮を剥いだレモンの原木");
            this.add(ModBlocks.STRIPPED_LEMON_WOOD.get(), "樹皮を剥いだレモンの木");
            this.add(ModBlocks.LEMON_PLANKS.get(), "レモンの板材");
            this.add(ModBlocks.LEMON_LEAVES.get(), "レモンの葉");
            this.add(ModBlocks.LEMON_SAPLING.get(), "レモンの苗木");
            this.add(ModBlocks.PLUM_LOG.get(), "梅の原木");
            this.add(ModBlocks.PLUM_WOOD.get(), "梅の木");
            this.add(ModBlocks.STRIPPED_PLUM_LOG.get(), "樹皮を剥いだ梅の原木");
            this.add(ModBlocks.STRIPPED_PLUM_WOOD.get(), "樹皮を剥いだ梅の木");
            this.add(ModBlocks.PLUM_PLANKS.get(), "梅の板材");
            this.add(ModBlocks.PLUM_LEAVES.get(), "梅の葉");
            this.add(ModBlocks.PLUM_SAPLING.get(), "梅の苗木");
            this.add(ModBlocks.CHERRY_LOG.get(), "サクランボの原木");
            this.add(ModBlocks.CHERRY_WOOD.get(), "サクランボの木");
            this.add(ModBlocks.STRIPPED_CHERRY_LOG.get(), "樹皮を剥いだサクランボの原木");
            this.add(ModBlocks.STRIPPED_CHERRY_WOOD.get(), "樹皮を剥いだサクランボの木");
            this.add(ModBlocks.CHERRY_PLANKS.get(), "サクランボの板材");
            this.add(ModBlocks.CHERRY_LEAVES.get(), "サクランボの葉");
            this.add(ModBlocks.CHERRY_SAPLING.get(), "サクランボの苗木");
            this.add(ModBlocks.BANANA_LOG.get(), "バナナの原木");
            this.add(ModBlocks.BANANA_WOOD.get(), "バナナの木");
            this.add(ModBlocks.STRIPPED_BANANA_LOG.get(), "樹皮を剥いだバナナの原木");
            this.add(ModBlocks.STRIPPED_BANANA_WOOD.get(), "樹皮を剥いだバナナの木");
            this.add(ModBlocks.BANANA_PLANKS.get(), "バナナの板材");
            this.add(ModBlocks.BANANA_LEAVES.get(), "バナナの葉");
            this.add(ModBlocks.BANANA_SAPLING.get(), "バナナの苗木");
            this.add(ModBlocks.PEACH_LOG.get(), "桃の原木");
            this.add(ModBlocks.PEACH_WOOD.get(), "桃の木");
            this.add(ModBlocks.STRIPPED_PEACH_LOG.get(), "樹皮を剥いだ桃の原木");
            this.add(ModBlocks.STRIPPED_PEACH_WOOD.get(), "樹皮を剥いだ桃の木");
            this.add(ModBlocks.PEACH_PLANKS.get(), "桃の板材");
            this.add(ModBlocks.PEACH_LEAVES.get(), "桃の葉");
            this.add(ModBlocks.PEACH_SAPLING.get(), "桃の苗木");
            this.add(ModBlocks.COCONUT_LOG.get(), "ココナッツの原木");
            this.add(ModBlocks.COCONUT_WOOD.get(), "ココナッツの木");
            this.add(ModBlocks.STRIPPED_COCONUT_LOG.get(), "樹皮を剥いだココナッツの原木");
            this.add(ModBlocks.STRIPPED_COCONUT_WOOD.get(), "樹皮を剥いだココナッツの木");
            this.add(ModBlocks.COCONUT_PLANKS.get(), "ココナッツの板材");
            this.add(ModBlocks.COCONUT_LEAVES.get(), "ココナッツの葉");
            this.add(ModBlocks.COCONUT_SAPLING.get(), "ココナッツの苗木");
            this.add(ModBlocks.ALMOND_LOG.get(), "アーモンドの原木");
            this.add(ModBlocks.ALMOND_WOOD.get(), "アーモンドの木");
            this.add(ModBlocks.STRIPPED_ALMOND_LOG.get(), "樹皮を剥いだアーモンドの原木");
            this.add(ModBlocks.STRIPPED_ALMOND_WOOD.get(), "樹皮を剥いだアーモンドの木");
            this.add(ModBlocks.ALMOND_PLANKS.get(), "アーモンドの板材");
            this.add(ModBlocks.ALMOND_LEAVES.get(), "アーモンドの葉");
            this.add(ModBlocks.ALMOND_SAPLING.get(), "アーモンドの苗木");
            this.add(ModBlocks.DURIAN_LOG.get(), "ドリアンの原木");
            this.add(ModBlocks.DURIAN_WOOD.get(), "ドリアンの木");
            this.add(ModBlocks.STRIPPED_DURIAN_LOG.get(), "樹皮を剥いだドリアンの原木");
            this.add(ModBlocks.STRIPPED_DURIAN_WOOD.get(), "樹皮を剥いだドリアンの木");
            this.add(ModBlocks.DURIAN_PLANKS.get(), "ドリアンの板材");
            this.add(ModBlocks.DURIAN_LEAVES.get(), "ドリアンの葉");
            this.add(ModBlocks.DURIAN_SAPLING.get(), "ドリアンの苗木");
            this.add(ModBlocks.COFFEE_LOG.get(), "コーヒーの原木");
            this.add(ModBlocks.COFFEE_WOOD.get(), "コーヒーの木");
            this.add(ModBlocks.STRIPPED_COFFEE_LOG.get(), "樹皮を剥いだコーヒーの原木");
            this.add(ModBlocks.STRIPPED_COFFEE_WOOD.get(), "樹皮を剥いだコーヒーの木");
            this.add(ModBlocks.COFFEE_PLANKS.get(), "コーヒーの板材");
            this.add(ModBlocks.COFFEE_LEAVES.get(), "コーヒーの葉");
            this.add(ModBlocks.COFFEE_SAPLING.get(), "コーヒーの苗木");
            this.add(ModBlocks.KIWI_LOG.get(), "キウイの原木");
            this.add(ModBlocks.KIWI_WOOD.get(), "キウイの木");
            this.add(ModBlocks.STRIPPED_KIWI_LOG.get(), "樹皮を剥いだキウイの原木");
            this.add(ModBlocks.STRIPPED_KIWI_WOOD.get(), "樹皮を剥いだキウイの木");
            this.add(ModBlocks.KIWI_PLANKS.get(), "キウイの板材");
            this.add(ModBlocks.KIWI_LEAVES.get(), "キウイの葉");
            this.add(ModBlocks.KIWI_SAPLING.get(), "キウイの苗木");
            this.add(ModBlocks.TEA_BUSH.get(), "お茶の木");
            this.add(ModBlocks.OLIVE_BUSH.get(), "オリーブの木");
            this.add(ModBlocks.BLUE_BERRY_BUSH.get(), "ブルーベリーの木");
            this.add(ModBlocks.HOP_BUSH.get(), "ホップの木");
            this.add(ModBlocks.PEPPER_BUSH.get(), "胡椒の木");
            this.add(ModBlocks.CABERNET_SAUVIGNON_STAIRS.get(), "カベルネ・ソーヴィニョンの階段");
            this.add(ModBlocks.CABERNET_SAUVIGNON_SLAB.get(), "カベルネ・ソーヴィニョンのハーフブロック");
            this.add(ModBlocks.CABERNET_SAUVIGNON_FENCE.get(), "カベルネ・ソーヴィニョンのフェンス");
            this.add(ModBlocks.CABERNET_SAUVIGNON_FENCE_GATE.get(), "カベルネ・ソーヴィニョンのフェンスゲート");
            //this.add(ModBlocks.CABERNET_SAUVIGNON_BUTTON.get(), "カベルネ・ソーヴィニョンのボタン");
            this.add(ModBlocks.CABERNET_SAUVIGNON_PRESSURE_PLATE.get(), "カベルネ・ソーヴィニョンの感圧版");
            this.add(ModBlocks.CABERNET_SAUVIGNON_DOOR.get(), "カベルネ・ソーヴィニョンのドア");
            this.add(ModBlocks.CABERNET_SAUVIGNON_TRAPDOOR.get(), "カベルネ・ソーヴィニョンのトラップドア");
            this.add(ModBlocks.MAPLE_STAIRS.get(), "メープルの階段");
            this.add(ModBlocks.MAPLE_SLAB.get(), "メープルのハーフブロック");
            this.add(ModBlocks.MAPLE_FENCE.get(), "メープルのフェンス");
            this.add(ModBlocks.MAPLE_FENCE_GATE.get(), "メープルのフェンスゲート");
            //this.add(ModBlocks.MAPLE_BUTTON.get(), "メープルのボタン");
            this.add(ModBlocks.MAPLE_PRESSURE_PLATE.get(), "メープルの感圧版");
            this.add(ModBlocks.MAPLE_DOOR.get(), "メープルのドア");
            this.add(ModBlocks.MAPLE_TRAPDOOR.get(), "メープルのトラップドア");
            this.add(ModBlocks.CINNAMON_STAIRS.get(), "シナモンの階段");
            this.add(ModBlocks.CINNAMON_SLAB.get(), "シナモンのハーフブロック");
            this.add(ModBlocks.CINNAMON_FENCE.get(), "シナモンのフェンス");
            this.add(ModBlocks.CINNAMON_FENCE_GATE.get(), "シナモンのフェンスゲート");
            //this.add(ModBlocks.CINNAMON_BUTTON.get(), "シナモンのボタン");
            this.add(ModBlocks.CINNAMON_PRESSURE_PLATE.get(), "シナモンの感圧版");
            this.add(ModBlocks.CINNAMON_DOOR.get(), "シナモンのドア");
            this.add(ModBlocks.CINNAMON_TRAPDOOR.get(), "シナモンのトラップドア");
            this.add(ModBlocks.COLA_STAIRS.get(), "コーラの階段");
            this.add(ModBlocks.COLA_SLAB.get(), "コーラのハーフブロック");
            this.add(ModBlocks.COLA_FENCE.get(), "コーラのフェンス");
            this.add(ModBlocks.COLA_FENCE_GATE.get(), "コーラのフェンスゲート");
            //this.add(ModBlocks.COLA_BUTTON.get(), "コーラのボタン");
            this.add(ModBlocks.COLA_PRESSURE_PLATE.get(), "コーラの感圧版");
            this.add(ModBlocks.COLA_DOOR.get(), "コーラのドア");
            this.add(ModBlocks.COLA_TRAPDOOR.get(), "コーラのトラップドア");
            this.add(ModBlocks.LEMON_STAIRS.get(), "レモンの階段");
            this.add(ModBlocks.LEMON_SLAB.get(), "レモンのハーフブロック");
            this.add(ModBlocks.LEMON_FENCE.get(), "レモンのフェンス");
            this.add(ModBlocks.LEMON_FENCE_GATE.get(), "レモンのフェンスゲート");
            //this.add(ModBlocks.LEMON_BUTTON.get(), "レモンのボタン");
            this.add(ModBlocks.LEMON_PRESSURE_PLATE.get(), "レモンの感圧版");
            this.add(ModBlocks.LEMON_DOOR.get(), "レモンのドア");
            this.add(ModBlocks.LEMON_TRAPDOOR.get(), "レモンのトラップドア");
            this.add(ModBlocks.PLUM_STAIRS.get(), "梅の階段");
            this.add(ModBlocks.PLUM_SLAB.get(), "梅のハーフブロック");
            this.add(ModBlocks.PLUM_FENCE.get(), "梅のフェンス");
            this.add(ModBlocks.PLUM_FENCE_GATE.get(), "梅のフェンスゲート");
            //this.add(ModBlocks.PLUM_BUTTON.get(), "梅のボタン");
            this.add(ModBlocks.PLUM_PRESSURE_PLATE.get(), "梅の感圧版");
            this.add(ModBlocks.PLUM_DOOR.get(), "梅のドア");
            this.add(ModBlocks.PLUM_TRAPDOOR.get(), "梅のトラップドア");
            this.add(ModBlocks.CHERRY_STAIRS.get(), "サクランボの階段");
            this.add(ModBlocks.CHERRY_SLAB.get(), "サクランボのハーフブロック");
            this.add(ModBlocks.CHERRY_FENCE.get(), "サクランボのフェンス");
            this.add(ModBlocks.CHERRY_FENCE_GATE.get(), "サクランボのフェンスゲート");
            //this.add(ModBlocks.CHERRY_BUTTON.get(), "サクランボのボタン");
            this.add(ModBlocks.CHERRY_PRESSURE_PLATE.get(), "サクランボの感圧版");
            this.add(ModBlocks.CHERRY_DOOR.get(), "サクランボのドア");
            this.add(ModBlocks.CHERRY_TRAPDOOR.get(), "サクランボのトラップドア");
            this.add(ModBlocks.BANANA_STAIRS.get(), "バナナの階段");
            this.add(ModBlocks.BANANA_SLAB.get(), "バナナのハーフブロック");
            this.add(ModBlocks.BANANA_FENCE.get(), "バナナのフェンス");
            this.add(ModBlocks.BANANA_FENCE_GATE.get(), "バナナのフェンスゲート");
            //this.add(ModBlocks.BANANA_BUTTON.get(), "バナナのボタン");
            this.add(ModBlocks.BANANA_PRESSURE_PLATE.get(), "バナナの感圧版");
            this.add(ModBlocks.BANANA_DOOR.get(), "バナナのドア");
            this.add(ModBlocks.BANANA_TRAPDOOR.get(), "バナナのトラップドア");
            this.add(ModBlocks.COCONUT_STAIRS.get(), "ココナッツの階段");
            this.add(ModBlocks.COCONUT_SLAB.get(), "ココナッツのハーフブロック");
            this.add(ModBlocks.COCONUT_FENCE.get(), "ココナッツのフェンス");
            this.add(ModBlocks.COCONUT_FENCE_GATE.get(), "ココナッツのフェンスゲート");
            //this.add(ModBlocks.COCONUT_BUTTON.get(), "ココナッツのボタン");
            this.add(ModBlocks.COCONUT_PRESSURE_PLATE.get(), "ココナッツの感圧版");
            this.add(ModBlocks.COCONUT_DOOR.get(), "ココナッツのドア");
            this.add(ModBlocks.COCONUT_TRAPDOOR.get(), "ココナッツのトラップドア");
            this.add(ModBlocks.PEACH_STAIRS.get(), "桃の階段");
            this.add(ModBlocks.PEACH_SLAB.get(), "桃のハーフブロック");
            this.add(ModBlocks.PEACH_FENCE.get(), "桃のフェンス");
            this.add(ModBlocks.PEACH_FENCE_GATE.get(), "桃のフェンスゲート");
            //this.add(ModBlocks.PEACH_BUTTON.get(), "桃のボタン");
            this.add(ModBlocks.PEACH_PRESSURE_PLATE.get(), "桃の感圧版");
            this.add(ModBlocks.PEACH_DOOR.get(), "桃のドア");
            this.add(ModBlocks.PEACH_TRAPDOOR.get(), "桃のトラップドア");
            this.add(ModBlocks.ALMOND_STAIRS.get(), "アーモンドの階段");
            this.add(ModBlocks.ALMOND_SLAB.get(), "アーモンドのハーフブロック");
            this.add(ModBlocks.ALMOND_FENCE.get(), "アーモンドのフェンス");
            this.add(ModBlocks.ALMOND_FENCE_GATE.get(), "アーモンドのフェンスゲート");
            //this.add(ModBlocks.ALMOND_BUTTON.get(), "アーモンドのボタン");
            this.add(ModBlocks.ALMOND_PRESSURE_PLATE.get(), "アーモンドの感圧版");
            this.add(ModBlocks.ALMOND_DOOR.get(), "アーモンドのドア");
            this.add(ModBlocks.ALMOND_TRAPDOOR.get(), "アーモンドのトラップドア");
            this.add(ModBlocks.DURIAN_STAIRS.get(), "ドリアンの階段");
            this.add(ModBlocks.DURIAN_SLAB.get(), "ドリアンのハーフブロック");
            this.add(ModBlocks.DURIAN_FENCE.get(), "ドリアンのフェンス");
            this.add(ModBlocks.DURIAN_FENCE_GATE.get(), "ドリアンのフェンスゲート");
            //this.add(ModBlocks.DURIAN_BUTTON.get(), "ドリアンのボタン");
            this.add(ModBlocks.DURIAN_PRESSURE_PLATE.get(), "ドリアンの感圧版");
            this.add(ModBlocks.DURIAN_DOOR.get(), "ドリアンのドア");
            this.add(ModBlocks.DURIAN_TRAPDOOR.get(), "ドリアンのトラップドア");
            this.add(ModBlocks.COFFEE_STAIRS.get(), "コーヒーの階段");
            this.add(ModBlocks.COFFEE_SLAB.get(), "コーヒーのハーフブロック");
            this.add(ModBlocks.COFFEE_FENCE.get(), "コーヒーのフェンス");
            this.add(ModBlocks.COFFEE_FENCE_GATE.get(), "コーヒーのフェンスゲート");
            //this.add(ModBlocks.DURIAN_BUTTON.get(), "ドリアンのボタン");
            this.add(ModBlocks.COFFEE_PRESSURE_PLATE.get(), "コーヒーの感圧版");
            this.add(ModBlocks.COFFEE_DOOR.get(), "コーヒーのドア");
            this.add(ModBlocks.COFFEE_TRAPDOOR.get(), "コーヒーのトラップドア");
            this.add(ModBlocks.KIWI_STAIRS.get(), "キウイの階段");
            this.add(ModBlocks.KIWI_SLAB.get(), "キウイのハーフブロック");
            this.add(ModBlocks.KIWI_FENCE.get(), "キウイのフェンス");
            this.add(ModBlocks.KIWI_FENCE_GATE.get(), "キウイのフェンスゲート");
            //this.add(ModBlocks.MAPLE_BUTTON.get(), "メープルのボタン");
            this.add(ModBlocks.KIWI_PRESSURE_PLATE.get(), "キウイの感圧版");
            this.add(ModBlocks.KIWI_DOOR.get(), "キウイのドア");
            this.add(ModBlocks.KIWI_TRAPDOOR.get(), "キウイのトラップドア");
            this.add(ModBlocks.QUEEN_OF_NIGHT.get(), "月下美人");
            this.add(ModBlocks.ROSE.get(), "バラ");
            this.add(ModBlocks.CAMOMILE.get(), "カモミール");
            this.add(ModBlocks.THYME.get(), "タイム");
            this.add(ModBlocks.OREGANO.get(), "オレガノ");
            this.add(ModBlocks.COFFEE_BLOCK.get(), "焙煎コーヒー豆");
            this.add(ModBlocks.RAW_COFFEE_BLOCK.get(), "生コーヒー豆");
            this.add(ModBlocks.MUSK_COFFEE_BLOCK.get(), "コピルアク豆");

            this.add(ModBlocks.CHROMITE_ORE.get(), "クローム鉱石");
            this.add(ModBlocks.DEEPSLATE_CHROMITE_ORE.get(), "深層クローム鉱石");
            this.add(ModBlocks.NETHERRACK_CHROMITE_ORE.get(), "ネザークローム鉱石");
            this.add(ModBlocks.FLUORITE_ORE.get(), "蛍石鉱石");
            this.add(ModBlocks.DEEPSLATE_FLUORITE_ORE.get(), "深層蛍石鉱石");
            this.add(ModBlocks.NETHERRACK_FLUORITE_ORE.get(), "ネザー蛍石鉱石");
            this.add(ModBlocks.ALUNITE_ORE.get(), "ミョウバン鉱石");
            this.add(ModBlocks.DEEPSLATE_ALUNITE_ORE.get(), "深層ミョウバン鉱石");
            this.add(ModBlocks.NETHERRACK_ALUNITE_ORE.get(), "ネザーミョウバン鉱石");
            this.add(ModBlocks.BAUXITE_ORE.get(), "ボーキサイト鉱石");
            this.add(ModBlocks.DEEPSLATE_BAUXITE_ORE.get(), "深層ボーキサイト鉱石");
            this.add(ModBlocks.NETHERRACK_BAUXITE_ORE.get(), "ネザーボーキサイト鉱石");
            this.add(ModBlocks.TITANIUM_ORE.get(), "チタン鉱石");
            this.add(ModBlocks.DEEPSLATE_TITANIUM_ORE.get(), "深層チタン鉱石");
            this.add(ModBlocks.NETHERRACK_TITANIUM_ORE.get(), "ネザーチタン鉱石");
            this.add(ModBlocks.MAGUNESIUM_ORE.get(), "マグネシウム鉱石");
            this.add(ModBlocks.DEEPSLATE_MAGUNESIUM_ORE.get(), "深層マグネシウム鉱石");
            this.add(ModBlocks.NETHERRACK_MAGUNESIUM_ORE.get(), "ネザーマグネシウム鉱石");
            this.add(ModBlocks.VANADIUM_ORE.get(), "バナジウム鉱石");
            this.add(ModBlocks.DEEPSLATE_VANADIUM_ORE.get(), "深層バナジウム鉱石");
            this.add(ModBlocks.NETHERRACK_VANADIUM_ORE.get(), "ネザーバナジウム鉱石");
            this.add(ModBlocks.CHROMITE_BLOCK.get(), "クロームブロック");
            this.add(ModBlocks.STAINLESS_BLOCK.get(), "ステンレスブロック");
            this.add(ModBlocks.FLUORITE_BLOCK.get(), "蛍石ブロック");
            this.add(ModBlocks.ALUNITE_BLOCK.get(), "ミョウバンブロック");
            this.add(ModBlocks.SANITARY_BLOCK.get(), "サニタリーブロック");
            this.add(ModBlocks.ALEXANDRITE_BLOCK.get(), "アレキサンドライト");
            this.add(ModBlocks.BLACK_DIAMOND_BLOCK.get(), "ブラックダイヤモンド");
            this.add(ModBlocks.CINNABAR_BLOCK.get(), "辰砂");
            this.add(ModBlocks.GOSHENITE_BLOCK.get(), "ゴーシェナイト");
            this.add(ModBlocks.MORGANITE_BLOCK.get(), "モルガナイト");
            this.add(ModBlocks.JADE_BLOCK.get(), "翡翠");
            this.add(ModBlocks.EUCLASE_BLOCK.get(), "ユークレイス");
            this.add(ModBlocks.RUTILE_BLOCK.get(), "ルチル");
            this.add(ModBlocks.PHOSPHOPHYLITE_BLOCK.get(), "フォスフォフィライト");
            this.add(ModBlocks.YELLOW_DIAMOND_BLOCK.get(), "イエローダイヤモンド");

            this.add(ModItems.BAKED_ALUM.get(), "焼きミョウバン");
            this.add(ModItems.STAINLESS.get(), "ステンレス");
            this.add(ModItems.DURALUMIN.get(), "ジュラルミン");
            this.add(ModItems.TITAN_ALLOY.get(), "チタン合金");
            this.add(ModItems.ELECTRON.get(), "エレクトロン");
            this.add(ModItems.VANADIUM_ALLOY.get(), "バナジウム合金");
            this.add(ModItems.CHROMITE_INGOT.get(), "クロームインゴット");
            this.add(ModItems.ALUMINIUM_INGOT.get(), "アルミニウムインゴット");
            this.add(ModItems.TITANIUM_INGOT.get(), "チタンインゴット");
            this.add(ModItems.MAGUNESIUM_INGOT.get(), "マグネシウムインゴット");
            this.add(ModItems.VANADIUM_INGOT.get(), "バナジウムインゴット");
            this.add(ModItems.ROW_CHROMITE.get(), "クロームの原石");
            this.add(ModItems.ROW_FLUORITE.get(), "蛍石の原石");
            this.add(ModItems.ROW_ALUNITE.get(), "ミョウバンの原石");
            this.add(ModItems.ROW_BAUXITE.get(), "ボーキサイトの原石");
            this.add(ModItems.ROW_TITANIUM.get(), "チタンの原石");
            this.add(ModItems.ROW_MAGUNESIUM.get(), "マグネシウムの原石");
            this.add(ModItems.ROW_VANADIUM.get(), "バナジウムの原石");

            this.add(ModItems.CABBAGE_LEAF.get(), "キャベツの葉");
            this.add(ModItems.ASPARAGUS.get(), "アスパラガス");
            this.add(ModItems.GRAPE.get(), "ブドウ");
            this.add(ModItems.LEMON.get(), "レモン");
            this.add(ModItems.PLUM.get(), "梅");
            this.add(ModItems.CHERRY.get(), "サクランボ");
            this.add(ModItems.BANANA.get(), "バナナ");
            this.add(ModItems.COCONUT.get(), "ココナッツ");
            this.add(ModItems.PEACH.get(), "ピーチ");
            this.add(ModItems.ALMOND.get(), "アーモンド");
            this.add(ModItems.ROW_COFFEE_BEANS.get(), "生のコーヒー豆");
            this.add(ModItems.COFFEE_BEANS.get(), "焙煎コーヒー豆");
            this.add(ModItems.MUSK_COFFEE_BEANS.get(), "コピルアク豆");
            this.add(ModItems.DURIAN.get(), "ドリアン");
            this.add(ModItems.CINNAMON.get(), "シナモン");
            this.add(ModItems.ROW_RICE.get(), "生米");
            this.add(ModItems.RICE.get(), "お米");
            this.add(ModItems.MINT.get(), "ミント");
            this.add(ModItems.COLA.get(), "コーラ");
            this.add(ModItems.TOMATO.get(), "トマト");
            this.add(ModItems.CORN.get(), "コーン");
            this.add(ModItems.ONION.get(), "玉ねぎ");
            this.add(ModItems.GINGER.get(), "ショウガ");
            this.add(ModItems.GREEN_PEPPER.get(), "ピーマン");
            this.add(ModItems.PAPRIKA.get(), "パプリカ");
            this.add(ModItems.EGGPLANT.get(), "ナス");
            this.add(ModItems.WHITE_RADISH.get(), "大根");
            this.add(ModItems.CHILI_PEPPER.get(), "唐辛子");
            this.add(ModItems.BASIL.get(), "バジル");
            this.add(ModItems.LOTUS_ROOT.get(), "レンコン");
            this.add(ModItems.ASPARAGUS_BACON.get(), "アスパラのベーコン巻き");
            this.add(ModItems.GINGER_PORK.get(), "生姜焼き");
            this.add(ModItems.FRIED_EGGPLANT.get(), "揚げナス");
            this.add(ModItems.CHINJAOLOSE.get(), "青椒肉絲");
            this.add(ModItems.POPCORN.get(), "ポップコーン");
            this.add(ModItems.PIZZA_BRED.get(), "ピザパン");
            this.add(ModItems.BOILED_FISH.get(), "煮魚");
            this.add(ModItems.CORN_SOUP.get(), "コーンスープ");
            this.add(ModItems.HAMBURGER.get(), "ハンバーガー");
            this.add(ModItems.TEA.get(), "お茶の葉");
            this.add(ModItems.OLIVE.get(), "オリーブ");
            this.add(ModItems.BLUE_BERRY.get(), "ブルーベリー");
            this.add(ModItems.HOP.get(), "ホップ");
            this.add(ModItems.PEPPER.get(), "胡椒");
            this.add(ModItems.ASPARAGUS_SEEDS.get(), "アスパラガスの種");
            this.add(ModItems.CABBAGE_SEEDS.get(), "キャベツの種");
            this.add(ModItems.RICE_SEEDS.get(), "米の種");
            this.add(ModItems.MINT_SEEDS.get(), "ミントの種");
            this.add(ModItems.COLA_SEEDS.get(), "コーラの種");
            this.add(ModItems.TOMATO_SEEDS.get(), "トマトの種");
            this.add(ModItems.CORN_SEEDS.get(), "コーンの種");
            this.add(ModItems.ONION_SEEDS.get(), "玉ねぎの種");
            this.add(ModItems.GINGER_SEEDS.get(), "ショウガの種");
            this.add(ModItems.GREEN_PEPPER_SEEDS.get(), "ピーマンの種");
            this.add(ModItems.PAPRIKA_SEEDS.get(), "パプリカの種");
            this.add(ModItems.EGGPLANT_SEEDS.get(), "ナスの種");
            this.add(ModItems.WHITE_RADISH_SEEDS.get(), "大根の種");
            this.add(ModItems.CHILI_PEPPER_SEEDS.get(), "唐辛子の種");
            this.add(ModItems.BASIL_SEEDS.get(), "バジルの種");
            this.add(ModItems.LOTUS_ROOT_SEEDS.get(), "レンコンの種");
            this.add(ModItems.PEPERONCINO.get(), "ペペロンチーノ");
            this.add(ModItems.MABO_NASU.get(), "麻婆茄子");
            this.add(ModItems.BAKED_CORN.get(), "焼きトウモロコシ");
            this.add(ModItems.RADISH_MINCED_MEAT.get(), "大根とひき肉炒め");
            this.add(ModItems.CHICKEN_EGG.get(), "親子丼");
            this.add(ModItems.GENOVESE.get(), "ジェノベーゼ");
            this.add(ModItems.FRIED_ALMOND.get(), "アーモンド素焼き");
            this.add(ModItems.GREEN_CARRY.get(), "グリーンカレー");
            this.add(ModItems.GREEN_PEPPER_MINCED_MEAT.get(), "ピーマンの肉詰め");
            this.add(ModItems.PEPE_CABBAGE.get(), "ペペチーキャベツ");
            this.add(ModItems.FRIED_LOTUS_ROOT.get(), "レンコンの素揚げ");
            this.add(ModItems.LOTUS_ROOT_MINCED_MEAT.get(), "レンコンの肉詰め");
            this.add(ModItems.GAPRAO.get(), "ガパオ");
            this.add(ModItems.TACOS.get(), "タコス");
            this.add(ModItems.TOMATO_SAND.get(), "トマトサンド");
            this.add(ModItems.BANANA_SAND.get(), "バナナサンド");
            this.add(ModItems.PEACH_SAND.get(), "ピーチサンド");
            this.add(ModItems.APPLE_SAND.get(), "アップルサンド");
            this.add(ModItems.GRAPE_SAND.get(), "グレープサンド");


            this.add(ModItems.FILTERED_WATER.get(), "濾過水");
            this.add(ModItems.BOTTLE_OF_MILK.get(), "牛乳");
            this.add(ModItems.BOTTLE_OF_WHISKEY.get(), "ウィスキー");
            this.add(ModItems.BOTTLE_OF_RED_WINE.get(), "赤ワイン");
            this.add(ModItems.BOTTLE_OF_WHITE_WINE.get(), "白ワイン");
            this.add(ModItems.BOTTLE_OF_WHITE_LIQUOR.get(), "ホワイトリカー");
            this.add(ModItems.PEACH_LIQUEUR.get(), "ピーチリキュール");
            this.add(ModItems.PLUM_LIQUEUR.get(), "梅酒");
            this.add(ModItems.LEMON_LIQUEUR.get(), "レモンリキュール");
            this.add(ModItems.MINT_LIQUEUR.get(), "ミントリキュール");
            this.add(ModItems.APPLE_LIQUEUR.get(), "リンゴリキュール");
            this.add(ModItems.MAPLE_WATER.get(), "楓水");
            this.add(ModItems.MAPLE_SYRUP.get(), "メープルシロップ");
            this.add(ModItems.BOTTLE_OF_COLA.get(), "コーラ");
            this.add(ModItems.GRAPE_JUICE.get(), "ぶどうジュース");
            this.add(ModItems.APPLE_JUICE.get(), "リンゴジュース");
            this.add(ModItems.LEMON_JUICE.get(), "レモンジュース");
            this.add(ModItems.PLUM_JUICE.get(), "梅ジュース");
            this.add(ModItems.PEACH_JUICE.get(), "桃ジュース");
            this.add(ModItems.BANANA_JUICE.get(), "バナナジュース");
            this.add(ModItems.ALMOND_MILK.get(), "アーモンドミルク");
            this.add(ModItems.COCONUT_MILK.get(), "ココナッツミルク");
            this.add(ModItems.SMOOTHIE.get(), "スムージー");
            this.add(ModItems.MIX_JUICE.get(), "ミックスジュース");
            this.add(ModItems.MIX_AU_LAIT.get(), "ミックスオレ");
            this.add(ModItems.CHOCOLATE.get(), "チョコレート");
            this.add(ModItems.CHOCO_MINT.get(), "チョコミント");
            this.add(ModItems.HABU.get(), "ハブのしっぽ");
            this.add(ModItems.HABU_LIQUEUR.get(), "ハブ酒");
            this.add(ModItems.COFFEE.get(), "コーヒー");
            this.add(ModItems.MUSK_COFFEE.get(), "コピルアク");

            this.add(ModItems.FILTERED_WATER_BUCKET.get(), "濾過水");
            this.add(ModItems.WHISKEY_BUCKET.get(), "ウイスキー");
            this.add(ModItems.MAPLE_BUCKET.get(), "メープルシロップ");
            this.add(ModItems.SAKE_BUCKET.get(), "酒");
            this.add(ModItems.WINE_BUCKET.get(), "赤ワイン");
            this.add(ModItems.WHITE_WINE_BUCKET.get(), "白ワイン");
            this.add(ModItems.J_MALT_BUCKET.get(), "麹");
            this.add(ModItems.RICE_BUCKET.get(), "蒸米");
            this.add(ModItems.MASH_BUCKET.get(), "もろみ");
            this.add(ModItems.YEAST_BUCKET.get(), "酒母");
            this.add(ModItems.JAPANESE_YEAST.get(), "酵母");

            this.add(ModItems.CHROMITE_AXE.get(), "クロームの斧");
            this.add(ModItems.CHROMITE_HOE.get(), "クロームのクワ");
            this.add(ModItems.CHROMITE_PICKAXE.get(), "クロームのピッケル");
            this.add(ModItems.CHROMITE_SHOVEL.get(), "クロームのシャベル");
            this.add(ModItems.CHROMITE_SWORD.get(), "クロームの剣");
            this.add(ModItems.FLUORITE_AXE.get(), "蛍石の斧");
            this.add(ModItems.FLUORITE_HOE.get(), "蛍石のクワ");
            this.add(ModItems.FLUORITE_PICKAXE.get(), "蛍石のピッケル");
            this.add(ModItems.FLUORITE_SHOVEL.get(), "蛍石のシャベル");
            this.add(ModItems.FLUORITE_SWORD.get(), "蛍石の剣");
            this.add(ModItems.ALUNITE_AXE.get(), "ミョウバンの斧");
            this.add(ModItems.ALUNITE_HOE.get(), "ミョウバンのクワ");
            this.add(ModItems.ALUNITE_PICKAXE.get(), "ミョウバンのピッケル");
            this.add(ModItems.ALUNITE_SHOVEL.get(), "ミョウバンのシャベル");
            this.add(ModItems.ALUNITE_SWORD.get(), "ミョウバンの剣");
            this.add(ModItems.STAINLESS_AXE.get(), "ステンレスの斧");
            this.add(ModItems.STAINLESS_HOE.get(), "ステンレスのクワ");
            this.add(ModItems.STAINLESS_PICKAXE.get(), "ステンレスのピッケル");
            this.add(ModItems.STAINLESS_SHOVEL.get(), "ステンレスのシャベル");
            this.add(ModItems.STAINLESS_SWORD.get(), "ステンレスの剣");
            this.add(ModItems.ALUMINIUM_AXE.get(), "アルミニウムの斧");
            this.add(ModItems.ALUMINIUM_HOE.get(), "アルミニウムのクワ");
            this.add(ModItems.ALUMINIUM_PICKAXE.get(), "アルミニウムのピッケル");
            this.add(ModItems.ALUMINIUM_SHOVEL.get(), "アルミニウムのシャベル");
            this.add(ModItems.ALUMINIUM_SWORD.get(), "アルミニウムの剣");
            this.add(ModItems.TITANIUM_AXE.get(), "チタンの斧");
            this.add(ModItems.TITANIUM_HOE.get(), "チタンのクワ");
            this.add(ModItems.TITANIUM_PICKAXE.get(), "チタンのピッケル");
            this.add(ModItems.TITANIUM_SHOVEL.get(), "チタンのシャベル");
            this.add(ModItems.TITANIUM_SWORD.get(), "チタンの剣");
            this.add(ModItems.MAGUNESIUM_AXE.get(), "マグネシウムの斧");
            this.add(ModItems.MAGUNESIUM_HOE.get(), "マグネシウムのクワ");
            this.add(ModItems.MAGUNESIUM_PICKAXE.get(), "マグネシウムのピッケル");
            this.add(ModItems.MAGUNESIUM_SHOVEL.get(), "マグネシウムのシャベル");
            this.add(ModItems.MAGUNESIUM_SWORD.get(), "マグネシウムの剣");
            this.add(ModItems.VANADIUM_AXE.get(), "バナジウムの斧");
            this.add(ModItems.VANADIUM_HOE.get(), "バナジウムのクワ");
            this.add(ModItems.VANADIUM_PICKAXE.get(), "バナジウムのピッケル");
            this.add(ModItems.VANADIUM_SHOVEL.get(), "バナジウムのシャベル");
            this.add(ModItems.VANADIUM_SWORD.get(), "バナジウムの剣");
            this.add(ModItems.DURALUMIN_AXE.get(), "ジュラルミンの斧");
            this.add(ModItems.DURALUMIN_HOE.get(), "ジュラルミンのクワ");
            this.add(ModItems.DURALUMIN_PICKAXE.get(), "ジュラルミンのピッケル");
            this.add(ModItems.DURALUMIN_SHOVEL.get(), "ジュラルミンのシャベル");
            this.add(ModItems.DURALUMIN_SWORD.get(), "ジュラルミンの剣");
            this.add(ModItems.TITAN_ALLOY_AXE.get(), "チタンの斧");
            this.add(ModItems.TITAN_ALLOY_HOE.get(), "チタンのクワ");
            this.add(ModItems.TITAN_ALLOY_PICKAXE.get(), "チタンのピッケル");
            this.add(ModItems.TITAN_ALLOY_SHOVEL.get(), "チタンのシャベル");
            this.add(ModItems.TITAN_ALLOY_SWORD.get(), "チタンの剣");
            this.add(ModItems.ELECTRON_AXE.get(), "エレクトロンの斧");
            this.add(ModItems.ELECTRON_HOE.get(), "エレクトロンのクワ");
            this.add(ModItems.ELECTRON_PICKAXE.get(), "エレクトロンのピッケル");
            this.add(ModItems.ELECTRON_SHOVEL.get(), "エレクトロンのシャベル");
            this.add(ModItems.ELECTRON_SWORD.get(), "エレクトロンの剣");
            this.add(ModItems.VANADIUM_ALLOY_AXE.get(), "バナジウムの斧");
            this.add(ModItems.VANADIUM_ALLOY_HOE.get(), "バナジウムのクワ");
            this.add(ModItems.VANADIUM_ALLOY_PICKAXE.get(), "バナジウムのピッケル");
            this.add(ModItems.VANADIUM_ALLOY_SHOVEL.get(), "バナジウムのシャベル");
            this.add(ModItems.VANADIUM_ALLOY_SWORD.get(), "バナジウムの剣");

            this.add(ModItems.HOOK_SHOT.get(), "フックショット");
            //this.add(ModBlocks.CREATE_TNT.get(), "創造のTNT");
            this.add(ModItems.SHIELD_CAST.get(), "リフレクター");
            this.add(ModItems.REVERSAL.get(), "洗脳の呪い");
            this.add(ModItems.GOLEM_SUMMON.get(), "クリエイト：ゴーレム");
            this.add(ModItems.ENDER_SPELL.get(), "エンドの禁書");
            this.add(ModItems.SOUL_SPELL.get(), "ソウルの禁書");
            this.add(ModItems.TONBOKIRI.get(), "蜻蛉切");
            this.add(ModItems.WOODEN_NET.get(), "木の網");
            this.add(ModItems.IRON_NET.get(), "鉄の網");
            this.add(ModItems.DIAMOND_NET.get(), "ダイアモンドの網");

            this.add(ModItems.CHROMITE_HELMET.get(), "クロームのヘルメット");
            this.add(ModItems.CHROMITE_CHESTPLATE.get(), "クロームのチェストプレート");
            this.add(ModItems.CHROMITE_LEGGINGS.get(), "クロームのレギンス");
            this.add(ModItems.CHROMITE_BOOTS.get(), "クロームのブーツ");
            this.add(ModItems.FLUORITE_HELMET.get(), "蛍石のヘルメット");
            this.add(ModItems.FLUORITE_CHESTPLATE.get(), "蛍石のチェストプレート");
            this.add(ModItems.FLUORITE_LEGGINGS.get(), "蛍石のレギンス");
            this.add(ModItems.FLUORITE_BOOTS.get(), "蛍石のブーツ");
            this.add(ModItems.STAINLESS_HELMET.get(), "ステンレスのヘルメット");
            this.add(ModItems.STAINLESS_CHESTPLATE.get(), "ステンレスのチェストプレート");
            this.add(ModItems.STAINLESS_LEGGINGS.get(), "ステンレスのレギンス");
            this.add(ModItems.STAINLESS_BOOTS.get(), "ステンレスのブーツ");
            this.add(ModItems.ALUMINIUM_HELMET.get(), "アルミニウムのヘルメット");
            this.add(ModItems.ALUMINIUM_CHESTPLATE.get(), "アルミニウムのチェストプレート");
            this.add(ModItems.ALUMINIUM_LEGGINGS.get(), "アルミニウムのレギンス");
            this.add(ModItems.ALUMINIUM_BOOTS.get(), "アルミニウムのブーツ");
            this.add(ModItems.TITANIUM_HELMET.get(), "チタンのヘルメット");
            this.add(ModItems.TITANIUM_CHESTPLATE.get(), "チタンのチェストプレート");
            this.add(ModItems.TITANIUM_LEGGINGS.get(), "チタンのレギンス");
            this.add(ModItems.TITANIUM_BOOTS.get(), "チタンのブーツ");
            this.add(ModItems.MAGUNESIUM_HELMET.get(), "マグネシウムのヘルメット");
            this.add(ModItems.MAGUNESIUM_CHESTPLATE.get(), "マグネシウムのチェストプレート");
            this.add(ModItems.MAGUNESIUM_LEGGINGS.get(), "マグネシウムのレギンス");
            this.add(ModItems.MAGUNESIUM_BOOTS.get(), "マグネシウムのブーツ");
            this.add(ModItems.VANADIUM_HELMET.get(), "バナジウムのヘルメット");
            this.add(ModItems.VANADIUM_CHESTPLATE.get(), "バナジウムのチェストプレート");
            this.add(ModItems.VANADIUM_LEGGINGS.get(), "バナジウムのレギンス");
            this.add(ModItems.VANADIUM_BOOTS.get(), "バナジウムのブーツ");
            this.add(ModItems.DURALUMIN_HELMET.get(), "ジュラルミンのヘルメット");
            this.add(ModItems.DURALUMIN_CHESTPLATE.get(), "ジュラルミンのチェストプレート");
            this.add(ModItems.DURALUMIN_LEGGINGS.get(), "ジュラルミンのレギンス");
            this.add(ModItems.DURALUMIN_BOOTS.get(), "ジュラルミンのブーツ");
            this.add(ModItems.TITAN_ALLOY_HELMET.get(), "チタン合金のヘルメット");
            this.add(ModItems.TITAN_ALLOY_CHESTPLATE.get(), "チタン合金のチェストプレート");
            this.add(ModItems.TITAN_ALLOY_LEGGINGS.get(), "チタン合金のレギンス");
            this.add(ModItems.TITAN_ALLOY_BOOTS.get(), "チタン合金のブーツ");
            this.add(ModItems.ELECTRON_HELMET.get(), "エレクトロンのヘルメット");
            this.add(ModItems.ELECTRON_CHESTPLATE.get(), "エレクトロンのチェストプレート");
            this.add(ModItems.ELECTRON_LEGGINGS.get(), "エレクトロンのレギンス");
            this.add(ModItems.ELECTRON_BOOTS.get(), "エレクトロンのブーツ");
            this.add(ModItems.VANADIUM_ALLOY_HELMET.get(), "バナジウム合金のヘルメット");
            this.add(ModItems.VANADIUM_ALLOY_CHESTPLATE.get(), "バナジウム合金のチェストプレート");
            this.add(ModItems.VANADIUM_ALLOY_LEGGINGS.get(), "バナジウム合金のレギンス");
            this.add(ModItems.VANADIUM_ALLOY_BOOTS.get(), "バナジウム合金のブーツ");

            this.add(ModBlocks.BFURNACE_BLOCK.get(), "高炉");
            this.add(ModBlocks.DISTILLER_BLOCK.get(), "蒸留機");
            this.add(ModBlocks.SAKE_DARU_BLOCK.get(), "醸造樽");
            this.add(ModBlocks.MIXER_BLOCK.get(), "ミキサー");
            this.add(ModBlocks.FRYPAN_BLOCK.get(), "フライパン");

            this.add(ModBlocks.PAMMUKALE_BLOCK.get(), "パムッカレの石");
            this.add(ModBlocks.SALT_BLOCK.get(), "塩");

            this.add(ModItems.FLY_BOAT.get(), "気球");
            this.add(ModItems.FLY_CHEST_BOAT.get(), "チェスト付き気球");

            this.add(ModItems.SPARROW_SPAWN_EGG.get(), "スズメのスポーンエッグ");
            this.add(ModItems.DEER_SPAWN_EGG.get(), "牡鹿のスポーンエッグ");
            this.add(ModItems.DOE_SPAWN_EGG.get(), "雌鹿のスポーンエッグ");

            this.add(ModEffects.SHIELD.get(), "シールドフィールド");
            this.add(ModEffects.MOON_WALK.get(), "ムーンウォーク");
            this.add(ModEffects.INV.get(), "不可視の呪い");
            this.add(ModEffects.MAGNETIC.get(), "マグネットフィールド");
            this.add(ModEffects.CRIME.get(), "クライマー");
            this.add(ModEffects.ARROW.get(), "オートタレット");
            this.add(ModEffects.HONEY.get(), "ハチミツ取り");
            this.add(ModEffects.INDICATE_HONEY.get(), "ハチミツ探し");
            this.add(ModEffects.WATER_FLOW.get(), "潤い");
            this.add(ModEffects.WATER_FALL.get(), "渇き");
            this.add(ModEffects.SNOW_WALK.get(), "雪歩き");
            this.add(ModEffects.DROWNED.get(), "酔い");
            this.add(ModEffects.DREAMER.get(), "夢歩き");

            this.add(ModEntityTypes.SPARROW.get(), "スズメ");
            this.add(ModEntityTypes.DEER.get(), "牡鹿");
            this.add(ModEntityTypes.DOE.get(), "雌鹿");
            this.add(ModEntityTypes.CICADA.get(), "セミ");
            this.add(ModEntityTypes.DRAGONFLY.get(), "トンボ");
            this.add(ModEntityTypes.BUTTERFLY.get(), "蝶々");
            this.add(ModEntityTypes.LONG_TIT.get(), "シマエナガ");
            this.add(ModEntityTypes.SEAL.get(), "アザラシ");
            this.add(ModEntityTypes.HERMIT_CRAB.get(), "ヤドカリ");
            this.add(ModEntityTypes.MINI_HIPO.get(), "コビトカバ");
            this.add(ModEntityTypes.MONGOOSE.get(), "マングース");
            this.add(ModEntityTypes.ANT.get(), "アリ");
            this.add(ModEntityTypes.SNAKE.get(), "ハブ");
            this.add(ModEntityTypes.PEACOCK.get(), "クジャク");
            this.add(ModEntityTypes.PERISSO.get(), "ハゲガオカザリドリ");
            this.add(ModEntityTypes.BURROWING_OWL.get(), "アナホリフクロウ");
            this.add(ModEntityTypes.FOLIVORE.get(), "ツメバケイ");
            this.add(ModEntityTypes.GIANT_OTTER.get(), "オオカワウソ");
            this.add(ModEntityTypes.GUYANA_RUPICOLA.get(), "ギアナイワドリ");
            this.add(ModEntityTypes.RATEL.get(), "ラーテル");
            this.add(ModEntityTypes.WOMBAT.get(), "ウォンバット");
            this.add(ModEntityTypes.HARPY_EAGLE.get(), "オオギワシ");
            this.add(ModEntityTypes.MUSK_CAT.get(), "ジャコウネコ");
            this.add(ModEntityTypes.BEAVER.get(), "ビーバー");
            this.add(ModEntityTypes.HAMMER_HEAD.get(), "シュモクザメ");
            this.add(ModEntityTypes.LEAFY_SEA.get(), "リーフィーシードラゴン");
            this.add(ModEntityTypes.KIWI.get(), "キウイ");
            this.add(ModEntityTypes.ROCK_PENGUIN.get(), "イワトビペンギン");
            this.add(ModEntityTypes.SKUNK.get(), "スカンク");
            this.add(ModEntityTypes.STURGEON.get(), "チョウザメ");
            this.add(ModEntityTypes.QUOKKA.get(), "クワッカワラビー");
            this.add(ModEntityTypes.WOOD_PECKER.get(), "キツツキ");
            this.add(ModEntityTypes.FELIS.get(), "スナネコ");
            this.add(ModEntityTypes.FRUIT_FLY.get(), "ショウジョウバエ");
            this.add(ModEntityTypes.INDICATOR_IDAE.get(), "ミツオシエ");
            this.add(ModEntityTypes.MANTIS_SHRIMP.get(), "モンハナシャコ");
            this.add(ModEntityTypes.MEERKAT.get(), "ミーアキャット");
            this.add(ModEntityTypes.PALLAS_CAT.get(), "マヌルネコ");
            this.add(ModEntityTypes.PANGOLIN.get(), "センザンコウ");
            this.add(ModEntityTypes.PORCUPINE.get(), "ヤマアラシ");
            this.add(ModEntityTypes.TAPIR.get(), "バク");
        }
    }

    public static class ModLangUS extends ModLangProvider {

        public ModLangUS(PackOutput output) {
            super(output, "en_us");
        }

        @Override
        protected void addTranslations() {

            this.add(ModBlocks.CABERNET_SAUVIGNON_LOG.get(), "Cabernet Sauvignon Wood");
            this.add(ModBlocks.CABERNET_SAUVIGNON_WOOD.get(), "Cabernet Sauvignon Log");
            this.add(ModBlocks.STRIPPED_CABERNET_SAUVIGNON_LOG.get(), "Stripped Cabernet Sauvignon Wood");
            this.add(ModBlocks.STRIPPED_CABERNET_SAUVIGNON_WOOD.get(), "Stripped Cabernet Sauvignon Log");
            this.add(ModBlocks.CABERNET_SAUVIGNON_PLANKS.get(), "Cabernet Sauvignon Planks");
            this.add(ModBlocks.CABERNET_SAUVIGNON_LEAVES.get(), "Cabernet Sauvignon Leaves");
            this.add(ModBlocks.CABERNET_SAUVIGNON_SAPLING.get(), "Cabernet Sauvignon Sapling");
            this.add(ModBlocks.MAPLE_LOG.get(), "Maple Wood");
            this.add(ModBlocks.MAPLE_WOOD.get(), "Maple Log");
            this.add(ModBlocks.STRIPPED_MAPLE_LOG.get(), "Stripped Maple Wood");
            this.add(ModBlocks.STRIPPED_MAPLE_WOOD.get(), "Stripped Maple Log");
            this.add(ModBlocks.MAPLE_PLANKS.get(), "Maple Planks");
            this.add(ModBlocks.MAPLE_LEAVES.get(), "Maple Leaves");
            this.add(ModBlocks.MAPLE_SAPLING.get(), "Maple Sapling");
            this.add(ModBlocks.CINNAMON_LOG.get(), "Cinnamon Wood");
            this.add(ModBlocks.CINNAMON_WOOD.get(), "Cinnamon Log");
            this.add(ModBlocks.STRIPPED_CINNAMON_LOG.get(), "Stripped Cinnamon Wood");
            this.add(ModBlocks.STRIPPED_CINNAMON_WOOD.get(), "Stripped Cinnamon Log");
            this.add(ModBlocks.CINNAMON_PLANKS.get(), "Cinnamon Planks");
            this.add(ModBlocks.CINNAMON_LEAVES.get(), "Cinnamon Leaves");
            this.add(ModBlocks.CINNAMON_SAPLING.get(), "Cinnamon Sapling");
            this.add(ModBlocks.COLA_LOG.get(), "Cola Wood");
            this.add(ModBlocks.COLA_WOOD.get(), "Cola Log");
            this.add(ModBlocks.STRIPPED_COLA_LOG.get(), "Stripped Cola Wood");
            this.add(ModBlocks.STRIPPED_COLA_WOOD.get(), "Stripped Cola Log");
            this.add(ModBlocks.COLA_PLANKS.get(), "Cola Planks");
            this.add(ModBlocks.COLA_LEAVES.get(), "Cola Leaves");
            this.add(ModBlocks.COLA_SAPLING.get(), "Cola Sapling");
            this.add(ModBlocks.LEMON_LOG.get(), "Lemon Wood");
            this.add(ModBlocks.LEMON_WOOD.get(), "Lemon Log");
            this.add(ModBlocks.STRIPPED_LEMON_LOG.get(), "Stripped Lemon Wood");
            this.add(ModBlocks.STRIPPED_LEMON_WOOD.get(), "Stripped Lemon Log");
            this.add(ModBlocks.LEMON_PLANKS.get(), "Lemon Planks");
            this.add(ModBlocks.LEMON_LEAVES.get(), "Lemon Leaves");
            this.add(ModBlocks.LEMON_SAPLING.get(), "Lemon Sapling");
            this.add(ModBlocks.PLUM_LOG.get(), "Plum Wood");
            this.add(ModBlocks.PLUM_WOOD.get(), "Plum Log");
            this.add(ModBlocks.STRIPPED_PLUM_LOG.get(), "Stripped Plum Wood");
            this.add(ModBlocks.STRIPPED_PLUM_WOOD.get(), "Stripped Plum Log");
            this.add(ModBlocks.PLUM_PLANKS.get(), "Plum Planks");
            this.add(ModBlocks.PLUM_LEAVES.get(), "Plum Leaves");
            this.add(ModBlocks.PLUM_SAPLING.get(), "Plum Sapling");
            this.add(ModBlocks.CHERRY_LOG.get(), "Cherry Wood");
            this.add(ModBlocks.CHERRY_WOOD.get(), "Cherry Log");
            this.add(ModBlocks.STRIPPED_CHERRY_LOG.get(), "Stripped Cherry Wood");
            this.add(ModBlocks.STRIPPED_CHERRY_WOOD.get(), "Stripped Cherry Log");
            this.add(ModBlocks.CHERRY_PLANKS.get(), "Cherry Planks");
            this.add(ModBlocks.CHERRY_LEAVES.get(), "Cherry Leaves");
            this.add(ModBlocks.CHERRY_SAPLING.get(), "Cherry Sapling");
            this.add(ModBlocks.BANANA_LOG.get(), "Banana Wood");
            this.add(ModBlocks.BANANA_WOOD.get(), "Banana Log");
            this.add(ModBlocks.STRIPPED_BANANA_LOG.get(), "Stripped Banana Wood");
            this.add(ModBlocks.STRIPPED_BANANA_WOOD.get(), "Stripped Banana Log");
            this.add(ModBlocks.BANANA_PLANKS.get(), "Banana Planks");
            this.add(ModBlocks.BANANA_LEAVES.get(), "Banana Leaves");
            this.add(ModBlocks.BANANA_SAPLING.get(), "Banana Sapling");
            this.add(ModBlocks.PEACH_LOG.get(), "Peach Wood");
            this.add(ModBlocks.PEACH_WOOD.get(), "Peach Log");
            this.add(ModBlocks.STRIPPED_PEACH_LOG.get(), "Stripped Peach Wood");
            this.add(ModBlocks.STRIPPED_PEACH_WOOD.get(), "Stripped Peach Log");
            this.add(ModBlocks.PEACH_PLANKS.get(), "Peach Planks");
            this.add(ModBlocks.PEACH_LEAVES.get(), "Peach Leaves");
            this.add(ModBlocks.PEACH_SAPLING.get(), "Peach Sapling");
            this.add(ModBlocks.COCONUT_LOG.get(), "Coconut Wood");
            this.add(ModBlocks.COCONUT_WOOD.get(), "Coconut Log");
            this.add(ModBlocks.STRIPPED_COCONUT_LOG.get(), "Stripped Coconut Wood");
            this.add(ModBlocks.STRIPPED_COCONUT_WOOD.get(), "Stripped Coconut Log");
            this.add(ModBlocks.COCONUT_PLANKS.get(), "Coconut Planks");
            this.add(ModBlocks.COCONUT_LEAVES.get(), "Coconut Leaves");
            this.add(ModBlocks.COCONUT_SAPLING.get(), "Coconut Sapling");
            this.add(ModBlocks.ALMOND_LOG.get(), "Almond Wood");
            this.add(ModBlocks.ALMOND_WOOD.get(), "Almond Log");
            this.add(ModBlocks.STRIPPED_ALMOND_LOG.get(), "Stripped Almond Wood");
            this.add(ModBlocks.STRIPPED_ALMOND_WOOD.get(), "Stripped Almond Log");
            this.add(ModBlocks.ALMOND_PLANKS.get(), "Almond Planks");
            this.add(ModBlocks.ALMOND_LEAVES.get(), "Almond Leaves");
            this.add(ModBlocks.ALMOND_SAPLING.get(), "Almond Sapling");
            this.add(ModBlocks.DURIAN_LOG.get(), "Durian Wood");
            this.add(ModBlocks.DURIAN_WOOD.get(), "Durian Log");
            this.add(ModBlocks.STRIPPED_DURIAN_LOG.get(), "Stripped Durian Wood");
            this.add(ModBlocks.STRIPPED_DURIAN_WOOD.get(), "Stripped Durian Log");
            this.add(ModBlocks.DURIAN_PLANKS.get(), "Durian Planks");
            this.add(ModBlocks.DURIAN_LEAVES.get(), "Durian Leaves");
            this.add(ModBlocks.DURIAN_SAPLING.get(), "Durian Sapling");
            this.add(ModBlocks.KIWI_LOG.get(), "Kiwi Wood");
            this.add(ModBlocks.KIWI_WOOD.get(), "Kiwi Log");
            this.add(ModBlocks.STRIPPED_KIWI_LOG.get(), "Stripped Kiwi Wood");
            this.add(ModBlocks.STRIPPED_KIWI_WOOD.get(), "Stripped Kiwi Log");
            this.add(ModBlocks.KIWI_PLANKS.get(), "Kiwi Planks");
            this.add(ModBlocks.KIWI_LEAVES.get(), "Kiwi Leaves");
            this.add(ModBlocks.KIWI_SAPLING.get(), "Kiwi Sapling");
            this.add(ModBlocks.TEA_BUSH.get(), "Tea Bush");
            this.add(ModBlocks.OLIVE_BUSH.get(), "Olive Bush");
            this.add(ModBlocks.BLUE_BERRY_BUSH.get(), "Blue Berry Bush");
            this.add(ModBlocks.HOP_BUSH.get(), "Hop Bush");
            this.add(ModBlocks.PEPPER_BUSH.get(), "Pepper Bush");
            this.add(ModBlocks.CABERNET_SAUVIGNON_STAIRS.get(), "Cabernet Sauvignon Stairs");
            this.add(ModBlocks.CABERNET_SAUVIGNON_SLAB.get(), "Cabernet Sauvignon Slab");
            this.add(ModBlocks.CABERNET_SAUVIGNON_FENCE.get(), "Cabernet Sauvignon Fence");
            this.add(ModBlocks.CABERNET_SAUVIGNON_FENCE_GATE.get(), "Cabernet Sauvignon Fence Gate");
            //this.add(ModBlocks.CABERNET_SAUVIGNON_BUTTON.get(), "Cabernet Sauvignon Button");
            this.add(ModBlocks.CABERNET_SAUVIGNON_PRESSURE_PLATE.get(), "Cabernet Sauvignon Pressure Plate");
            this.add(ModBlocks.CABERNET_SAUVIGNON_DOOR.get(), "Cabernet Sauvignon Door");
            this.add(ModBlocks.CABERNET_SAUVIGNON_TRAPDOOR.get(), "Cabernet Sauvignon Trap Door");
            this.add(ModBlocks.MAPLE_STAIRS.get(), "Maple Stairs");
            this.add(ModBlocks.MAPLE_SLAB.get(), "Maple Slab");
            this.add(ModBlocks.MAPLE_FENCE.get(), "Maple Fence");
            this.add(ModBlocks.MAPLE_FENCE_GATE.get(), "Maple Fence Gate");
            //this.add(ModBlocks.MAPLE_BUTTON.get(), "Maple Button");
            this.add(ModBlocks.MAPLE_PRESSURE_PLATE.get(), "Maple Pressure Plate");
            this.add(ModBlocks.MAPLE_DOOR.get(), "Maple Door");
            this.add(ModBlocks.MAPLE_TRAPDOOR.get(), "Maple Trap Door");
            this.add(ModBlocks.CINNAMON_STAIRS.get(), "Cinnamon Stairs");
            this.add(ModBlocks.CINNAMON_SLAB.get(), "Cinnamon Slab");
            this.add(ModBlocks.CINNAMON_FENCE.get(), "Cinnamon Fence");
            this.add(ModBlocks.CINNAMON_FENCE_GATE.get(), "Cinnamon Fence Gate");
            //this.add(ModBlocks.CINNAMON_BUTTON.get(), "Cinnamon Button");
            this.add(ModBlocks.CINNAMON_PRESSURE_PLATE.get(), "Cinnamon Pressure Plate");
            this.add(ModBlocks.CINNAMON_DOOR.get(), "Cinnamon Door");
            this.add(ModBlocks.CINNAMON_TRAPDOOR.get(), "Cinnamon Trap Door");
            this.add(ModBlocks.COLA_STAIRS.get(), "Cola Stairs");
            this.add(ModBlocks.COLA_SLAB.get(), "Cola Slab");
            this.add(ModBlocks.COLA_FENCE.get(), "Cola Fence");
            this.add(ModBlocks.COLA_FENCE_GATE.get(), "Cola Fence Gate");
            //this.add(ModBlocks.COLA_BUTTON.get(), "Cola Button");
            this.add(ModBlocks.COLA_PRESSURE_PLATE.get(), "Cola Pressure Plate");
            this.add(ModBlocks.COLA_DOOR.get(), "Cola Door");
            this.add(ModBlocks.COLA_TRAPDOOR.get(), "Cola Trap Door");
            this.add(ModBlocks.LEMON_STAIRS.get(), "Lemon Stairs");
            this.add(ModBlocks.LEMON_SLAB.get(), "Lemon Slab");
            this.add(ModBlocks.LEMON_FENCE.get(), "Lemon Fence");
            this.add(ModBlocks.LEMON_FENCE_GATE.get(), "Lemon Fence Gate");
            //this.add(ModBlocks.LEMON_BUTTON.get(), "Lemon Button");
            this.add(ModBlocks.LEMON_PRESSURE_PLATE.get(), "Lemon Pressure Plate");
            this.add(ModBlocks.LEMON_DOOR.get(), "Lemon Door");
            this.add(ModBlocks.LEMON_TRAPDOOR.get(), "Lemon Trap Door");
            this.add(ModBlocks.PLUM_STAIRS.get(), "Plum Stairs");
            this.add(ModBlocks.PLUM_SLAB.get(), "Plum Slab");
            this.add(ModBlocks.PLUM_FENCE.get(), "Plum Fence");
            this.add(ModBlocks.PLUM_FENCE_GATE.get(), "Plum Fence Gate");
            //this.add(ModBlocks.PLUM_BUTTON.get(), "Plum Button");
            this.add(ModBlocks.PLUM_PRESSURE_PLATE.get(), "Plum Pressure Plate");
            this.add(ModBlocks.PLUM_DOOR.get(), "Plum Door");
            this.add(ModBlocks.PLUM_TRAPDOOR.get(), "Plum Trap Door");
            this.add(ModBlocks.CHERRY_STAIRS.get(), "Cherry Stairs");
            this.add(ModBlocks.CHERRY_SLAB.get(), "Cherry Slab");
            this.add(ModBlocks.CHERRY_FENCE.get(), "Cherry Fence");
            this.add(ModBlocks.CHERRY_FENCE_GATE.get(), "Cherry Fence Gate");
            //this.add(ModBlocks.CHERRY_BUTTON.get(), "Cherry Button");
            this.add(ModBlocks.CHERRY_PRESSURE_PLATE.get(), "Cherry Pressure Plate");
            this.add(ModBlocks.CHERRY_DOOR.get(), "Cherry Door");
            this.add(ModBlocks.CHERRY_TRAPDOOR.get(), "Cherry Trap Door");
            this.add(ModBlocks.BANANA_STAIRS.get(), "Banana Stairs");
            this.add(ModBlocks.BANANA_SLAB.get(), "Banana Slab");
            this.add(ModBlocks.BANANA_FENCE.get(), "Banana Fence");
            this.add(ModBlocks.BANANA_FENCE_GATE.get(), "Banana Fence Gate");
            //this.add(ModBlocks.BANANA_BUTTON.get(), "Banana Button");
            this.add(ModBlocks.BANANA_PRESSURE_PLATE.get(), "Banana Pressure Plate");
            this.add(ModBlocks.BANANA_DOOR.get(), "Banana Door");
            this.add(ModBlocks.BANANA_TRAPDOOR.get(), "Banana Trap Door");
            this.add(ModBlocks.COCONUT_STAIRS.get(), "Coconut Stairs");
            this.add(ModBlocks.COCONUT_SLAB.get(), "Coconut Slab");
            this.add(ModBlocks.COCONUT_FENCE.get(), "Coconut Fence");
            this.add(ModBlocks.COCONUT_FENCE_GATE.get(), "Coconut Fence Gate");
            //this.add(ModBlocks.COCONUT_BUTTON.get(), "Coconut Button");
            this.add(ModBlocks.COCONUT_PRESSURE_PLATE.get(), "Coconut Pressure Plate");
            this.add(ModBlocks.COCONUT_DOOR.get(), "Coconut Door");
            this.add(ModBlocks.COCONUT_TRAPDOOR.get(), "Coconut Trap Door");
            this.add(ModBlocks.PEACH_STAIRS.get(), "Peach Stairs");
            this.add(ModBlocks.PEACH_SLAB.get(), "Peach Slab");
            this.add(ModBlocks.PEACH_FENCE.get(), "Peach Fence");
            this.add(ModBlocks.PEACH_FENCE_GATE.get(), "Peach Fence Gate");
            //this.add(ModBlocks.PEACH_BUTTON.get(), "Peach Button");
            this.add(ModBlocks.PEACH_PRESSURE_PLATE.get(), "Peach Pressure Plate");
            this.add(ModBlocks.PEACH_DOOR.get(), "Peach Door");
            this.add(ModBlocks.PEACH_TRAPDOOR.get(), "Peach Trap Door");
            this.add(ModBlocks.ALMOND_STAIRS.get(), "Almond Stairs");
            this.add(ModBlocks.ALMOND_SLAB.get(), "Almond Slab");
            this.add(ModBlocks.ALMOND_FENCE.get(), "Almond Fence");
            this.add(ModBlocks.ALMOND_FENCE_GATE.get(), "Almond Fence Gate");
            //this.add(ModBlocks.ALMOND_BUTTON.get(), "Almond Button");
            this.add(ModBlocks.ALMOND_PRESSURE_PLATE.get(), "Almond Pressure Plate");
            this.add(ModBlocks.ALMOND_DOOR.get(), "Almond Door");
            this.add(ModBlocks.ALMOND_TRAPDOOR.get(), "Almond Trap Door");
            this.add(ModBlocks.DURIAN_STAIRS.get(), "Durian Stairs");
            this.add(ModBlocks.DURIAN_SLAB.get(), "Durian Slab");
            this.add(ModBlocks.DURIAN_FENCE.get(), "Durian Fence");
            this.add(ModBlocks.DURIAN_FENCE_GATE.get(), "Durian Fence Gate");
            //this.add(ModBlocks.DURIAN_BUTTON.get(), "Durian Button");
            this.add(ModBlocks.DURIAN_PRESSURE_PLATE.get(), "Durian Pressure Plate");
            this.add(ModBlocks.DURIAN_DOOR.get(), "Durian Door");
            this.add(ModBlocks.DURIAN_TRAPDOOR.get(), "Durian Trap Door");
            this.add(ModBlocks.KIWI_STAIRS.get(), "Kiwi Stairs");
            this.add(ModBlocks.KIWI_SLAB.get(), "Kiwi Slab");
            this.add(ModBlocks.KIWI_FENCE.get(), "Kiwi Fence");
            this.add(ModBlocks.KIWI_FENCE_GATE.get(), "Kiwi Fence Gate");
            //this.add(ModBlocks.MAPLE_BUTTON.get(), "Maple Button");
            this.add(ModBlocks.KIWI_PRESSURE_PLATE.get(), "Kiwi Pressure Plate");
            this.add(ModBlocks.KIWI_DOOR.get(), "Kiwi Door");
            this.add(ModBlocks.KIWI_TRAPDOOR.get(), "Kiwi Trap Door");
            this.add(ModBlocks.QUEEN_OF_NIGHT.get(), "Queen Of Night");
            this.add(ModBlocks.ROSE.get(), "Rose");
            this.add(ModBlocks.CAMOMILE.get(), "Camomile");
            this.add(ModBlocks.THYME.get(), "Thyme");
            this.add(ModBlocks.OREGANO.get(), "Oregano");

            this.add(ModBlocks.CHROMITE_ORE.get(), "Chrome Ore");
            this.add(ModBlocks.DEEPSLATE_CHROMITE_ORE.get(), "Deepslate Chrome Ore");
            this.add(ModBlocks.NETHERRACK_CHROMITE_ORE.get(), "Nether Chrome Ore");
            this.add(ModBlocks.FLUORITE_ORE.get(), "Fluorite Ore");
            this.add(ModBlocks.DEEPSLATE_FLUORITE_ORE.get(), "Deepslate Fluorite Ore");
            this.add(ModBlocks.NETHERRACK_FLUORITE_ORE.get(), "Nether Fluorite Ore");
            this.add(ModBlocks.ALUNITE_ORE.get(), "Alunite Ore");
            this.add(ModBlocks.DEEPSLATE_ALUNITE_ORE.get(), "Deepslate Alunite Ore");
            this.add(ModBlocks.NETHERRACK_ALUNITE_ORE.get(), "Nether Alunite Ore");
            this.add(ModBlocks.BAUXITE_ORE.get(), "Bauxite Ore");
            this.add(ModBlocks.DEEPSLATE_BAUXITE_ORE.get(), "Deepslate Bauxite Ore");
            this.add(ModBlocks.NETHERRACK_BAUXITE_ORE.get(), "Nether Bauxite Ore");
            this.add(ModBlocks.TITANIUM_ORE.get(), "Titanium Ore");
            this.add(ModBlocks.DEEPSLATE_TITANIUM_ORE.get(), "Deepslate Titanium Ore");
            this.add(ModBlocks.NETHERRACK_TITANIUM_ORE.get(), "Nether Titanium Ore");
            this.add(ModBlocks.MAGUNESIUM_ORE.get(), "Magunesium Ore");
            this.add(ModBlocks.DEEPSLATE_MAGUNESIUM_ORE.get(), "Deepslate Magunesium Ore");
            this.add(ModBlocks.NETHERRACK_MAGUNESIUM_ORE.get(), "Nether Magunesium Ore");
            this.add(ModBlocks.VANADIUM_ORE.get(), "Vanadium Ore");
            this.add(ModBlocks.DEEPSLATE_VANADIUM_ORE.get(), "Deepslate Vanadium Ore");
            this.add(ModBlocks.NETHERRACK_VANADIUM_ORE.get(), "Nether Vanadium Ore");
            this.add(ModBlocks.CHROMITE_BLOCK.get(), "Chrome Block");
            this.add(ModBlocks.STAINLESS_BLOCK.get(), "Stainless Block");
            this.add(ModBlocks.FLUORITE_BLOCK.get(), "Fluorite Block");
            this.add(ModBlocks.ALUNITE_BLOCK.get(), "Alunite Block");
            this.add(ModBlocks.SANITARY_BLOCK.get(), "Sanitary Block");

            this.add(ModItems.BAKED_ALUM.get(), "Baked Alunite");
            this.add(ModItems.STAINLESS.get(), "Stainless");
            this.add(ModItems.DURALUMIN.get(), "Duralumin");
            this.add(ModItems.TITAN_ALLOY.get(), "Titanium Alloy");
            this.add(ModItems.ELECTRON.get(), "Electron");
            this.add(ModItems.VANADIUM_ALLOY.get(), "Vanadium Alloy");
            this.add(ModItems.CHROMITE_INGOT.get(), "Chrome Ingot");
            this.add(ModItems.ALUMINIUM_INGOT.get(), "Aluminium Ingot");
            this.add(ModItems.TITANIUM_INGOT.get(), "Titanium Ingot");
            this.add(ModItems.MAGUNESIUM_INGOT.get(), "Magunesium Ingot");
            this.add(ModItems.VANADIUM_INGOT.get(), "Vanadium Ingot");
            this.add(ModItems.ROW_CHROMITE.get(), "Chrome");
            this.add(ModItems.ROW_FLUORITE.get(), "Fluorite");
            this.add(ModItems.ROW_ALUNITE.get(), "Alunite");
            this.add(ModItems.ROW_BAUXITE.get(), "Bauxite");
            this.add(ModItems.ROW_TITANIUM.get(), "Titanium");
            this.add(ModItems.ROW_MAGUNESIUM.get(), "Magunesium");
            this.add(ModItems.ROW_VANADIUM.get(), "Vanadium");

            this.add(ModItems.CABBAGE_LEAF.get(), "Cabbage Leaves");
            this.add(ModItems.ASPARAGUS.get(), "Asparagus");
            this.add(ModItems.GRAPE.get(), "Grape");
            this.add(ModItems.LEMON.get(), "Lemon");
            this.add(ModItems.PLUM.get(), "Plum");
            this.add(ModItems.CHERRY.get(), "Cherry");
            this.add(ModItems.BANANA.get(), "Banana");
            this.add(ModItems.COCONUT.get(), "Coconut");
            this.add(ModItems.PEACH.get(), "Peach");
            this.add(ModItems.ALMOND.get(), "Almond");
            this.add(ModItems.DURIAN.get(), "Durian");
            this.add(ModItems.CINNAMON.get(), "Cinnamon");
            this.add(ModItems.ROW_RICE.get(), "Row Rice");
            this.add(ModItems.RICE.get(), "Rice");
            this.add(ModItems.MINT.get(), "Mint");
            this.add(ModItems.COLA.get(), "Cola");
            this.add(ModItems.TOMATO.get(), "Tomato");
            this.add(ModItems.CORN.get(), "Corn");
            this.add(ModItems.ONION.get(), "Onion");
            this.add(ModItems.GINGER.get(), "Ginger");
            this.add(ModItems.GREEN_PEPPER.get(), "Green Pepper");
            this.add(ModItems.PAPRIKA.get(), "Paprika");
            this.add(ModItems.EGGPLANT.get(), "Eggplant");
            this.add(ModItems.WHITE_RADISH.get(), "Radish");
            this.add(ModItems.CHILI_PEPPER.get(), "Chili Pepper");
            this.add(ModItems.BASIL.get(), "Basil");
            this.add(ModItems.LOTUS_ROOT.get(), "Lotus Root");
            this.add(ModItems.ASPARAGUS_BACON.get(), "Asparagus Bacon");
            this.add(ModItems.GINGER_PORK.get(), "Ginger Pork");
            this.add(ModItems.FRIED_EGGPLANT.get(), "Fried Eggplant");
            this.add(ModItems.CHINJAOLOSE.get(), "Chinjiaolose");
            this.add(ModItems.POPCORN.get(), "Popcorn");
            this.add(ModItems.PIZZA_BRED.get(), "Pizza Bread");
            this.add(ModItems.BOILED_FISH.get(), "Boiled Fish");
            this.add(ModItems.CORN_SOUP.get(), "Corn Soup");
            this.add(ModItems.HAMBURGER.get(), "Hamburger");
            this.add(ModItems.TEA.get(), "Tea Leaves");
            this.add(ModItems.OLIVE.get(), "Olive");
            this.add(ModItems.BLUE_BERRY.get(), "Blue Berry");
            this.add(ModItems.HOP.get(), "Hop");
            this.add(ModItems.PEPPER.get(), "Pepper");
            this.add(ModItems.ASPARAGUS_SEEDS.get(), "Asparagus Seeds");
            this.add(ModItems.CABBAGE_SEEDS.get(), "Cabbage Seeds");
            this.add(ModItems.RICE_SEEDS.get(), "Rice Seeds");
            this.add(ModItems.MINT_SEEDS.get(), "Mint Seeds");
            this.add(ModItems.COLA_SEEDS.get(), "Cola Seeds");
            this.add(ModItems.TOMATO_SEEDS.get(), "Tomato Seeds");
            this.add(ModItems.CORN_SEEDS.get(), "Corn Seeds");
            this.add(ModItems.ONION_SEEDS.get(), "Onion Seeds");
            this.add(ModItems.GINGER_SEEDS.get(), "Ginger Seeds");
            this.add(ModItems.GREEN_PEPPER_SEEDS.get(), "Green Pepper Seeds");
            this.add(ModItems.PAPRIKA_SEEDS.get(), "Paprika Seeds");
            this.add(ModItems.EGGPLANT_SEEDS.get(), "Eggplant Seeds");
            this.add(ModItems.WHITE_RADISH_SEEDS.get(), "Radish Seeds");
            this.add(ModItems.CHILI_PEPPER_SEEDS.get(), "Chili Pepper Seeds");
            this.add(ModItems.BASIL_SEEDS.get(), "Basil Seeds");
            this.add(ModItems.LOTUS_ROOT_SEEDS.get(), "Lotus Root Seeds");
            this.add(ModItems.PEPERONCINO.get(), "Peperoncino");
            this.add(ModItems.MABO_NASU.get(), "Mabo Egg Plant");
            this.add(ModItems.BAKED_CORN.get(), "Baked Corn");
            this.add(ModItems.RADISH_MINCED_MEAT.get(), "Radish with Minced Meat");
            this.add(ModItems.CHICKEN_EGG.get(), "Chicken and Egg");
            this.add(ModItems.GENOVESE.get(), "Genovese");
            this.add(ModItems.FRIED_ALMOND.get(), "Baked Almond");
            this.add(ModItems.GREEN_CARRY.get(), "Green Carry");
            this.add(ModItems.GREEN_PEPPER_MINCED_MEAT.get(), "Green Pepper with Minced Meat");
            this.add(ModItems.PEPE_CABBAGE.get(), "PEPE Cabbage");
            this.add(ModItems.FRIED_LOTUS_ROOT.get(), "Fried Lotus Root");
            this.add(ModItems.LOTUS_ROOT_MINCED_MEAT.get(), "Lotus Root with Minced Meat");
            this.add(ModItems.GAPRAO.get(), "Gaprao");
            this.add(ModItems.TACOS.get(), "Tacos");
            this.add(ModItems.TOMATO_SAND.get(), "Tomato Sand");
            this.add(ModItems.BANANA_SAND.get(), "Banana Sand");
            this.add(ModItems.PEACH_SAND.get(), "Peach Sand");
            this.add(ModItems.APPLE_SAND.get(), "Apple Sand");
            this.add(ModItems.GRAPE_SAND.get(), "Grape Sand");

            this.add(ModItems.FILTERED_WATER.get(), "Filtered Water");
            this.add(ModItems.BOTTLE_OF_MILK.get(), "Milk");
            this.add(ModItems.BOTTLE_OF_WHISKEY.get(), "Whisky");
            this.add(ModItems.BOTTLE_OF_RED_WINE.get(), "Red Wine");
            this.add(ModItems.BOTTLE_OF_WHITE_WINE.get(), "White Wine");
            this.add(ModItems.BOTTLE_OF_SAKE.get(), "Sake");
            this.add(ModItems.BOTTLE_OF_WHITE_LIQUOR.get(), "White Liquor");
            this.add(ModItems.PEACH_LIQUEUR.get(), "Peach Liqueur");
            this.add(ModItems.PLUM_LIQUEUR.get(), "Plum Liqueur");
            this.add(ModItems.LEMON_LIQUEUR.get(), "Lemon Liqueur");
            this.add(ModItems.MINT_LIQUEUR.get(), "Mint Liqueur");
            this.add(ModItems.APPLE_LIQUEUR.get(), "Apple Liqueur");
            this.add(ModItems.MAPLE_WATER.get(), "Maple Water");
            this.add(ModItems.MAPLE_SYRUP.get(), "Maple Syrup");
            this.add(ModItems.BOTTLE_OF_COLA.get(), "Cola");
            this.add(ModItems.GRAPE_JUICE.get(), "Grape Juice");
            this.add(ModItems.APPLE_JUICE.get(), "Apple Juice");
            this.add(ModItems.LEMON_JUICE.get(), "Lemon Juice");
            this.add(ModItems.PLUM_JUICE.get(), "Plum Juice");
            this.add(ModItems.PEACH_JUICE.get(), "Peach Juice");
            this.add(ModItems.BANANA_JUICE.get(), "Banana Juice");
            this.add(ModItems.ALMOND_MILK.get(), "Almond Milk");
            this.add(ModItems.COCONUT_MILK.get(), "Coconut Milk");
            this.add(ModItems.SMOOTHIE.get(), "Smoothie");
            this.add(ModItems.MIX_JUICE.get(), "Mix Juice");
            this.add(ModItems.MIX_AU_LAIT.get(), "Mix Au Lait");
            this.add(ModItems.CHOCOLATE.get(), "Chocolate");
            this.add(ModItems.CHOCO_MINT.get(), "Chocolate Mint");

            this.add(ModItems.CHROMITE_AXE.get(), "Chrome Axe");
            this.add(ModItems.CHROMITE_HOE.get(), "Chrome Hoe");
            this.add(ModItems.CHROMITE_PICKAXE.get(), "Chrome Pickaxe");
            this.add(ModItems.CHROMITE_SHOVEL.get(), "Chrome Shovel");
            this.add(ModItems.CHROMITE_SWORD.get(), "Chrome Sword");
            this.add(ModItems.FLUORITE_AXE.get(), "Fluorite Axe");
            this.add(ModItems.FLUORITE_HOE.get(), "Fluorite Hoe");
            this.add(ModItems.FLUORITE_PICKAXE.get(), "Fluorite Pickaxe");
            this.add(ModItems.FLUORITE_SHOVEL.get(), "Fluorite Shovel");
            this.add(ModItems.FLUORITE_SWORD.get(), "Fluorite Sword");
            this.add(ModItems.ALUNITE_AXE.get(), "Alunite Axe");
            this.add(ModItems.ALUNITE_HOE.get(), "Alunite Hoe");
            this.add(ModItems.ALUNITE_PICKAXE.get(), "Alunite Pickaxe");
            this.add(ModItems.ALUNITE_SHOVEL.get(), "Alunite Shovel");
            this.add(ModItems.ALUNITE_SWORD.get(), "Alunite Sword");
            this.add(ModItems.STAINLESS_AXE.get(), "Stainless Axe");
            this.add(ModItems.STAINLESS_HOE.get(), "Stainless Hoe");
            this.add(ModItems.STAINLESS_PICKAXE.get(), "Stainless Pickaxe");
            this.add(ModItems.STAINLESS_SHOVEL.get(), "Stainless Shovel");
            this.add(ModItems.STAINLESS_SWORD.get(), "Stainless Sword");
            this.add(ModItems.ALUMINIUM_AXE.get(), "Aluminium Axe");
            this.add(ModItems.ALUMINIUM_HOE.get(), "Aluminium Hoe");
            this.add(ModItems.ALUMINIUM_PICKAXE.get(), "Aluminium Pickaxe");
            this.add(ModItems.ALUMINIUM_SHOVEL.get(), "Aluminium Shovel");
            this.add(ModItems.ALUMINIUM_SWORD.get(), "Aluminium Sword");
            this.add(ModItems.TITANIUM_AXE.get(), "Titanium Axe");
            this.add(ModItems.TITANIUM_HOE.get(), "Titanium Hoe");
            this.add(ModItems.TITANIUM_PICKAXE.get(), "Titanium Pickaxe");
            this.add(ModItems.TITANIUM_SHOVEL.get(), "Titanium Shovel");
            this.add(ModItems.TITANIUM_SWORD.get(), "Titanium Sword");
            this.add(ModItems.MAGUNESIUM_AXE.get(), "Magunesium Axe");
            this.add(ModItems.MAGUNESIUM_HOE.get(), "Magunesium Hoe");
            this.add(ModItems.MAGUNESIUM_PICKAXE.get(), "Magunesium Pickaxe");
            this.add(ModItems.MAGUNESIUM_SHOVEL.get(), "Magunesium Shovel");
            this.add(ModItems.MAGUNESIUM_SWORD.get(), "Magunesium Sword");
            this.add(ModItems.VANADIUM_AXE.get(), "Vanadium Axe");
            this.add(ModItems.VANADIUM_HOE.get(), "Vanadium Hoe");
            this.add(ModItems.VANADIUM_PICKAXE.get(), "Vanadium Pickaxe");
            this.add(ModItems.VANADIUM_SHOVEL.get(), "Vanadium Shovel");
            this.add(ModItems.VANADIUM_SWORD.get(), "Vanadium Sword");
            this.add(ModItems.DURALUMIN_AXE.get(), "Duralumin Axe");
            this.add(ModItems.DURALUMIN_HOE.get(), "Duralumin Hoe");
            this.add(ModItems.DURALUMIN_PICKAXE.get(), "Duralumin Pickaxe");
            this.add(ModItems.DURALUMIN_SHOVEL.get(), "Duralumin Shovel");
            this.add(ModItems.DURALUMIN_SWORD.get(), "Duralumin Sword");
            this.add(ModItems.TITAN_ALLOY_AXE.get(), "Titanium Axe");
            this.add(ModItems.TITAN_ALLOY_HOE.get(), "Titanium Hoe");
            this.add(ModItems.TITAN_ALLOY_PICKAXE.get(), "Titanium Pickaxe");
            this.add(ModItems.TITAN_ALLOY_SHOVEL.get(), "Titanium Shovel");
            this.add(ModItems.TITAN_ALLOY_SWORD.get(), "Titanium Sword");
            this.add(ModItems.ELECTRON_AXE.get(), "Electron Axe");
            this.add(ModItems.ELECTRON_HOE.get(), "Electron Hoe");
            this.add(ModItems.ELECTRON_PICKAXE.get(), "Electron Pickaxe");
            this.add(ModItems.ELECTRON_SHOVEL.get(), "Electron Shovel");
            this.add(ModItems.ELECTRON_SWORD.get(), "Electron Sword");
            this.add(ModItems.VANADIUM_ALLOY_AXE.get(), "Vanadium Axe");
            this.add(ModItems.VANADIUM_ALLOY_HOE.get(), "Vanadium Hoe");
            this.add(ModItems.VANADIUM_ALLOY_PICKAXE.get(), "Vanadium Pickaxe");
            this.add(ModItems.VANADIUM_ALLOY_SHOVEL.get(), "Vanadium Shovel");
            this.add(ModItems.VANADIUM_ALLOY_SWORD.get(), "Vanadium Sword");

            this.add(ModItems.HOOK_SHOT.get(), "Hook Shot");

            this.add(ModItems.CHROMITE_HELMET.get(), "Chrome Helmet");
            this.add(ModItems.CHROMITE_CHESTPLATE.get(), "Chrome Chestplate");
            this.add(ModItems.CHROMITE_LEGGINGS.get(), "Chrome Leggings");
            this.add(ModItems.CHROMITE_BOOTS.get(), "Chrome Boots");
            this.add(ModItems.FLUORITE_HELMET.get(), "Fluorite Helmet");
            this.add(ModItems.FLUORITE_CHESTPLATE.get(), "Fluorite Chestplate");
            this.add(ModItems.FLUORITE_LEGGINGS.get(), "Fluorite Leggings");
            this.add(ModItems.FLUORITE_BOOTS.get(), "Fluorite Boots");
            this.add(ModItems.STAINLESS_HELMET.get(), "Stainless Helmet");
            this.add(ModItems.STAINLESS_CHESTPLATE.get(), "Stainless Chestplate");
            this.add(ModItems.STAINLESS_LEGGINGS.get(), "Stainless Leggings");
            this.add(ModItems.STAINLESS_BOOTS.get(), "Stainless Boots");
            this.add(ModItems.ALUMINIUM_HELMET.get(), "Aluminium Helmet");
            this.add(ModItems.ALUMINIUM_CHESTPLATE.get(), "Aluminium Chestplate");
            this.add(ModItems.ALUMINIUM_LEGGINGS.get(), "Aluminium Leggings");
            this.add(ModItems.ALUMINIUM_BOOTS.get(), "Aluminium Boots");
            this.add(ModItems.TITANIUM_HELMET.get(), "Titanium Helmet");
            this.add(ModItems.TITANIUM_CHESTPLATE.get(), "Titanium Chestplate");
            this.add(ModItems.TITANIUM_LEGGINGS.get(), "Titanium Leggings");
            this.add(ModItems.TITANIUM_BOOTS.get(), "Titanium Boots");
            this.add(ModItems.MAGUNESIUM_HELMET.get(), "Magunesium Helmet");
            this.add(ModItems.MAGUNESIUM_CHESTPLATE.get(), "Magunesium Chestplate");
            this.add(ModItems.MAGUNESIUM_LEGGINGS.get(), "Magunesium Leggings");
            this.add(ModItems.MAGUNESIUM_BOOTS.get(), "Magunesium Boots");
            this.add(ModItems.VANADIUM_HELMET.get(), "Vanadium Helmet");
            this.add(ModItems.VANADIUM_CHESTPLATE.get(), "Vanadium Chestplate");
            this.add(ModItems.VANADIUM_LEGGINGS.get(), "Vanadium Leggings");
            this.add(ModItems.VANADIUM_BOOTS.get(), "Vanadium Boots");
            this.add(ModItems.DURALUMIN_HELMET.get(), "Duralumin Helmet");
            this.add(ModItems.DURALUMIN_CHESTPLATE.get(), "Duralumin Chestplate");
            this.add(ModItems.DURALUMIN_LEGGINGS.get(), "Duralumin Leggings");
            this.add(ModItems.DURALUMIN_BOOTS.get(), "Duralumin Boots");
            this.add(ModItems.TITAN_ALLOY_HELMET.get(), "Titanium Alloy Helmet");
            this.add(ModItems.TITAN_ALLOY_CHESTPLATE.get(), "Titanium Alloy Chestplate");
            this.add(ModItems.TITAN_ALLOY_LEGGINGS.get(), "Titanium Alloy Leggings");
            this.add(ModItems.TITAN_ALLOY_BOOTS.get(), "Titanium Alloy Boots");
            this.add(ModItems.ELECTRON_HELMET.get(), "Electron Helmet");
            this.add(ModItems.ELECTRON_CHESTPLATE.get(), "Electron Chestplate");
            this.add(ModItems.ELECTRON_LEGGINGS.get(), "Electron Leggings");
            this.add(ModItems.ELECTRON_BOOTS.get(), "Electron Boots");
            this.add(ModItems.VANADIUM_ALLOY_HELMET.get(), "Vanadium Alloy Helmet");
            this.add(ModItems.VANADIUM_ALLOY_CHESTPLATE.get(), "Vanadium Alloy Chestplate");
            this.add(ModItems.VANADIUM_ALLOY_LEGGINGS.get(), "Vanadium Alloy Leggings");
            this.add(ModItems.VANADIUM_ALLOY_BOOTS.get(), "Vanadium Alloy Boots");

            this.add(ModBlocks.BFURNACE_BLOCK.get(), "Blast Furnace");
            this.add(ModBlocks.DISTILLER_BLOCK.get(), "Distiller");
            this.add(ModBlocks.SAKE_DARU_BLOCK.get(), "Aging Barrel");
            this.add(ModBlocks.MIXER_BLOCK.get(), "Mixer");
            this.add(ModBlocks.FRYPAN_BLOCK.get(), "Pan");

            this.add(ModItems.SPARROW_SPAWN_EGG.get(), "Sparrow Spawn Egg");
            this.add(ModItems.DEER_SPAWN_EGG.get(), "Deer Spawn Egg");
            this.add(ModItems.DOE_SPAWN_EGG.get(), "Doe Spawn Egg");

            this.add(ModEntityTypes.SPARROW.get(), "スズメ");
            this.add(ModEntityTypes.DEER.get(), "牡鹿");
            this.add(ModEntityTypes.DOE.get(), "雌鹿");
            this.add(ModEntityTypes.CICADA.get(), "セミ");
            this.add(ModEntityTypes.DRAGONFLY.get(), "トンボ");
            this.add(ModEntityTypes.BUTTERFLY.get(), "蝶々");
            this.add(ModEntityTypes.LONG_TIT.get(), "シマエナガ");
            this.add(ModEntityTypes.SEAL.get(), "アザラシ");
            this.add(ModEntityTypes.HERMIT_CRAB.get(), "ヤドカリ");
            this.add(ModEntityTypes.MINI_HIPO.get(), "コビトカバ");
            this.add(ModEntityTypes.MONGOOSE.get(), "マングース");
            this.add(ModEntityTypes.ANT.get(), "アリ");
            this.add(ModEntityTypes.SNAKE.get(), "ハブ");
            this.add(ModEntityTypes.PEACOCK.get(), "クジャク");
            this.add(ModEntityTypes.PERISSO.get(), "ハゲガオカザリドリ");
            this.add(ModEntityTypes.BURROWING_OWL.get(), "アナホリフクロウ");
            this.add(ModEntityTypes.FOLIVORE.get(), "ツメバケイ");
            this.add(ModEntityTypes.GIANT_OTTER.get(), "オオカワウソ");
            this.add(ModEntityTypes.GUYANA_RUPICOLA.get(), "ギアナイワドリ");
            this.add(ModEntityTypes.RATEL.get(), "ラーテル");
            this.add(ModEntityTypes.WOMBAT.get(), "ウォンバット");
            this.add(ModEntityTypes.HARPY_EAGLE.get(), "オオギワシ");
            this.add(ModEntityTypes.MUSK_CAT.get(), "ジャコウネコ");
            this.add(ModEntityTypes.BEAVER.get(), "ビーバー");
            this.add(ModEntityTypes.HAMMER_HEAD.get(), "シュモクザメ");
            this.add(ModEntityTypes.LEAFY_SEA.get(), "リーフィーシードラゴン");
            this.add(ModEntityTypes.KIWI.get(), "キウイ");
            this.add(ModEntityTypes.ROCK_PENGUIN.get(), "イワトビペンギン");
            this.add(ModEntityTypes.SKUNK.get(), "スカンク");
            this.add(ModEntityTypes.STURGEON.get(), "チョウザメ");
            this.add(ModEntityTypes.QUOKKA.get(), "クワッカワラビー");
            this.add(ModEntityTypes.WOOD_PECKER.get(), "キツツキ");
            this.add(ModEntityTypes.FELIS.get(), "スナネコ");
            this.add(ModEntityTypes.FRUIT_FLY.get(), "ショウジョウバエ");
            this.add(ModEntityTypes.INDICATOR_IDAE.get(), "ミツオシエ");
            this.add(ModEntityTypes.MANTIS_SHRIMP.get(), "モンハナシャコ");
            this.add(ModEntityTypes.MEERKAT.get(), "ミーアキャット");
            this.add(ModEntityTypes.PALLAS_CAT.get(), "マヌルネコ");
            this.add(ModEntityTypes.PANGOLIN.get(), "センザンコウ");
            this.add(ModEntityTypes.PORCUPINE.get(), "ヤマアラシ");
            this.add(ModEntityTypes.TAPIR.get(), "バク");
        }
    }
}
